"""Python wrapper for MonoRTM (MONOchromatic Radiative Transfer Model).

MonoRTM is a Fortran radiative transfer model from AER Inc. that computes
atmospheric microwave brightness temperatures.

This wrapper supports MonoRTM v5.x from https://github.com/AER-RC/monoRTM

Usage:
    rtm = MonoRTM(monortm_path='/usr/local/bin/monortm')
    tb = rtm.simulate(profile)  # profile is dict with T, RH, CLWC, height

Input format:
    MonoRTM reads two files in the working directory:
    1. MONORTM.IN - control file (TAPE5 format)
    2. MONORTM_PROF.IN - atmospheric profile data (for IATM=0)

    Plus TAPE3 - spectral line data (symlinked from installation).
"""

import os
import subprocess
import tempfile
import shutil
import numpy as np
import config


class MonoRTM:
    """Python interface to the MonoRTM Fortran executable.

    Example:
        rtm = MonoRTM(monortm_path='/usr/local/bin/monortm',
                       tape3_path='/usr/local/share/monortm/TAPE3')
        tb = rtm.simulate(profile)
        tb_batch = rtm.simulate_batch(profiles_dict)
    """

    # Default RPG HATPRO frequencies in wavenumber [cm^-1]
    # Conversion: wavenumber = frequency_GHz / 0.0299792458
    FREQ_GHZ_TO_CM1 = 1.0 / 0.0299792458

    def __init__(self, monortm_path=None, tape3_path=None, frequencies=None):
        """
        Args:
            monortm_path: path to monoRTM executable
            tape3_path: path to TAPE3 spectral line data file
        """
        if monortm_path is None:
            monortm_path = self._find_executable()
        self.monortm_path = monortm_path
        self._check_executable()

        if tape3_path is None:
            tape3_path = self._find_tape3()
        self.tape3_path = tape3_path

        self.frequencies = frequencies if frequencies is not None else config.ALL_CHANNELS  # GHz

    def _find_executable(self):
        """Find MonoRTM executable."""
        candidates = [
            os.environ.get("MONORTM_PATH", ""),
            os.path.join(os.path.dirname(__file__), "..", "bin", "monortm_fixed"),
            os.path.join(os.path.dirname(__file__), "..", "bin", "monortm_linux"),
            os.path.join(os.path.dirname(__file__), "..", "bin", "monortm"),
            "/usr/local/bin/monortm",
            "/opt/homebrew/bin/monortm",
        ]
        for path in candidates:
            if path and os.path.isfile(path):
                return path
        return "monortm"

    def _find_tape3(self):
        """Find TAPE3 spectral line data file. Prefers binary format."""
        project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
        candidates = [
            os.environ.get("MONORTM_TAPE3", ""),
            # Binary TAPE3 (generated by convert_tape3.py)
            os.path.join(project_root, "data", "TAPE3", "TAPE3_bin"),
            os.path.join(project_root, "data", "TAPE3", "TAPE3"),
            os.path.join(project_root, "data", "TAPE3",
                         "spectral_lines.dat.0_55.v5.0_fast"),
            os.path.join(os.path.dirname(self.monortm_path), "..", "run", "in",
                         "TAPE3_spectral_lines.dat.0_55.v5.0_fast"),
            "/tmp/monortm_src/run/in/TAPE3_spectral_lines.dat.0_55.v5.0_fast",
        ]
        for path in candidates:
            if path and os.path.isfile(path) and os.path.getsize(path) > 100000:
                return path
        # Last resort: shallow search near executable (skip venv/node_modules)
        exe_dir = os.path.dirname(os.path.abspath(self.monortm_path))
        search_root = os.path.dirname(exe_dir)
        for root, dirs, files in os.walk(search_root):
            dirs[:] = [d for d in dirs if d not in (".venv", ".git", "node_modules", "__pycache__")]
            for f in files:
                if f == "TAPE3":
                    fp = os.path.join(root, f)
                    if os.path.getsize(fp) > 100000:
                        return fp
                if "TAPE3" in f and "spectral" in f and os.path.getsize(os.path.join(root, f)) > 100000:
                    return os.path.join(root, f)
        return None

    def _check_executable(self):
        if not os.path.isfile(self.monortm_path):
            raise FileNotFoundError(
                f"MonoRTM executable not found: '{self.monortm_path}'\n"
                f"Build it: build_monortm.sh\n"
                f"Or set MONORTM_PATH environment variable."
            )

    def _make_monortm_in(self, frequencies_ghz, tmpdir):
        """Generate MONORTM.IN control file for IATM=0 (user profile).

        Record layout follows the standard MonoRTM TAPE5 format.
        """
        # Convert frequencies to wavenumbers [cm^-1]
        wn = [f / 0.0299792458 for f in frequencies_ghz]

        lines = []
        lines.append(" MWR retrieval: downwelling brightness temperature simulation")
        lines.append("HIRAC LBLF CNTM AERS EMIT SCAN FLTR PLOT TEST IATM IMRG ILAS  IOD XSCT MPTS NPTS      ISPD")
        lines.append("$ Rundeck")

        # Record 1.1: flags. IATM=0 means user-defined atmosphere
        # fmt: HI=1 LBLFLG=1 CNTMFLG=1 AERSFLG=0 EMIT=1 SCAN=0 FLTR=1 PLOT=1
        #      TEST=0 IATM=0 IMRG=0 ILAS=0 IOD=0 XSCT=0 MPTS=0 NPTS=0 ISPD=0
        # PLOT=1 is required to output brightness temperatures
        lines.append("    1    1    1    0    1    0    1    1    0    0    0    0    0    0    0    0    0    0")

        # Record 1.2: bounds
        lines.append("-0.200E+00 8.800E+00 0.000E+00 0.100E-00 0.000E+00 0.000E+00 0.000E+00 0.000E+00    0      0.000E+00    0")

        # Record 1.3: frequency list
        lines.append(str(len(wn)))
        for w in wn:
            lines.append(f"{w:.6f}")

        # Record 1.4: additional parameters
        lines.append("     0.    1.0       0.000E+00 0.000E+00 0.000E+00 0.000E+00 0.000E+00")

        # End record
        lines.append("    6    2    0    1    1    7    1")
        lines.append("     0.000    30.000       0.000")
        lines.append("     0.000     3.000     3.000     0.000     0.000")
        lines.append("-1")
        lines.append("%%%%%%%%%%%%%%%%")
        lines.append("     0.000     0.000     0.000     0.000     0.000")

        return "\n".join(lines)

    def _make_monortm_prof_in(self, profile):
        """Generate MONORTM_PROF.IN with exact MonoRTM v5.6 Fortran column FORMAT.

        FORMAT reference (from monortm.f90):
          Header 925: (1X,I1,I3,I5,F10.6,2A8,4X,F8.2,4X,F8.2,5X,F8.3,5X,I2) — 80 cols
          Layer  975: (E15.7,2F10.4,3X,I2,1X,2(F7.2,F8.3,F7.2),F7.3) — 92 cols, IFORM=1, 1st layer
          Layer 9752: (E15.7,2F10.4,3X,I2,1X,22X,1(F7.2,F8.3,F7.2),F7.3) — subsequent layers
          Mol    978: (8E15.7) — WKL(1:7)+WBRODL then WKL(8:NMOL)

        Constraint: NMOL−7 ≤ 8 → NMOL ≤ 15 (otherwise 2nd mol line crosses record boundary).
        """
        # ---- atmospheric state arrays ----
        T = np.asarray(profile["T"], dtype=np.float64)
        RH = np.asarray(profile["RH"], dtype=np.float64)
        heights_m = np.asarray(profile["height"], dtype=np.float64)
        heights_km = heights_m / 1000.0
        n_layers = len(heights_m)

        # CLWC (cloud liquid water content) [g/m³] — optional, default 0
        if "CLWC" in profile:
            clwc_arr = np.asarray(profile["CLWC"], dtype=np.float64)
        else:
            clwc_arr = np.zeros(n_layers, dtype=np.float64)

        # ---- pressure at layer centres [hPa] ----
        if "P_hPa" in profile:
            P = np.asarray(profile["P_hPa"], dtype=np.float64)
        elif "P" in profile:
            P = np.asarray(profile["P"], dtype=np.float64)
        else:
            P = 1013.25 * np.exp(-heights_m / 8000.0)

        # ---- layer boundaries (n_layers+1 levels) ----
        # boundary altitudes at midpoints between layer centres
        bnd_km = np.zeros(n_layers + 1, dtype=np.float64)
        bnd_P = np.zeros(n_layers + 1, dtype=np.float64)
        bnd_T = np.zeros(n_layers + 1, dtype=np.float64)

        bnd_km[0] = 0.0
        bnd_T[0] = T[0]
        # surface pressure: extrapolate from first two layers
        if n_layers > 1:
            r = np.log(P[0] / P[1]) / (heights_km[1] - heights_km[0])
            bnd_P[0] = P[0] * np.exp(r * heights_km[0])
        else:
            bnd_P[0] = P[0] * 1.02

        for i in range(1, n_layers):
            bnd_km[i] = (heights_km[i - 1] + heights_km[i]) * 0.5
            bnd_T[i] = (T[i - 1] + T[i]) * 0.5
            bnd_P[i] = np.exp((np.log(P[i - 1]) + np.log(P[i])) * 0.5)

        # top boundary
        bnd_km[-1] = heights_km[-1] + (heights_km[-1] - heights_km[-2]) * 0.5
        bnd_T[-1] = T[-1]
        bnd_P[-1] = P[-1] * np.exp(
            -(bnd_km[-1] - heights_km[-1]) * 1000.0 / (287.058 * T[-1]) * 9.80665 * P[-1] * 100.0 / (P[-1] * 100.0)
        )
        # simpler: log-extrapolate
        r_top = np.log(P[-2] / P[-1]) / (heights_km[-1] - heights_km[-2])
        bnd_P[-1] = P[-1] * np.exp(-r_top * (bnd_km[-1] - heights_km[-1]))
        bnd_P[-1] = max(bnd_P[-1], 1e-3)

        # ---- constants ----
        g = 9.80665          # m/s²
        M_dry = 0.0289644    # kg/mol
        N_A = 6.02214076e23  # molec/mol
        # dry-air column per hPa: ΔP_hPa * 100 [Pa/hPa] / (g*M_dry) * N_A * 1e-4 [m²/cm²]
        COL_PER_HPA = 100.0 / (g * M_dry) * N_A * 1e-4  # ≈ 2.12e21 molec/cm² per hPa

        # ---- Molecule set (NMOL=15) ----
        nmol = 15
        iform = 1          # IFORM=1: E15.7 pressure
        secnt0 = 1.000000  # zenith
        hmod = "USER    USER    "   # 16 chars (2A8)
        angle = 0.0        # zenith → ground-based looking up (IRT=3)
        ilen = 0

        # ---- header (FORMAT 925, exactly 80 cols) ----
        # col 1:1X, 2:I1, 3-5:I3, 6-10:I5, 11-20:F10.6, 21-36:2A8,
        #      37-40:4X, 41-48:F8.2, 49-52:4X, 53-60:F8.2,
        #      61-65:5X, 66-73:F8.3, 74-78:5X, 79-80:I2
        header = (
            f" {iform:1d}{n_layers:3d}{nmol:5d}{secnt0:10.6f}{hmod:16s}"
            f"    {0.00:8.2f}    {heights_km[-1]:8.2f}"
            f"     {angle:8.3f}     {ilen:2d}"
        )
        assert len(header) == 80, f"Header length {len(header)} != 80"

        lines = [header]

        # ---- standard volume mixing ratios (all < 1, treated as mixing ratio) ----
        # Indices 2..15 (Fortran 2..NMOL)
        std_vmr = {
            2: 4.20e-04,   # CO2
            3: 3.00e-08,   # O3
            4: 3.20e-07,   # N2O
            5: 1.00e-07,   # CO
            6: 1.90e-06,   # CH4
            7: 2.09e-01,   # O2
            8: 1.00e-09,   # NO
            9: 1.00e-10,   # SO2
            10: 1.00e-09,  # NO2
            11: 1.00e-10,  # NH3
            12: 1.00e-09,  # HNO3
            13: 1.00e-13,  # OH
            14: 1.00e-10,  # HF
            15: 1.00e-10,  # HCL
        }

        for il in range(n_layers):
            p = float(P[il])
            t = float(T[il])
            rh = float(RH[il])
            secnt = 1.0
            ipath = 3          # internal layer boundary
            clwc = float(clwc_arr[il])

            alt_bot = float(bnd_km[il])
            p_bot = float(bnd_P[il])
            t_bot = float(bnd_T[il])
            alt_top = float(bnd_km[il + 1])
            p_top = float(bnd_P[il + 1])
            t_top = float(bnd_T[il + 1])

            # ---- layer record (FORMAT 975 / 9752) ----
            if il == 0:
                # FORMAT 975: (E15.7,2F10.4,3X,I2,1X,2(F7.2,F8.3,F7.2),F7.3)
                layer_line = (
                    f"{p:15.7E}{t:10.4f}{secnt:10.4f}   {ipath:2d} "
                    f"{alt_bot:7.2f}{p_bot:8.3f}{t_bot:7.2f}"
                    f"{alt_top:7.2f}{p_top:8.3f}{t_top:7.2f}"
                    f"{clwc:7.3f}"
                )
            else:
                # FORMAT 9752: (E15.7,2F10.4,3X,I2,1X,22X,1(F7.2,F8.3,F7.2),F7.3)
                layer_line = (
                    f"{p:15.7E}{t:10.4f}{secnt:10.4f}   {ipath:2d} "
                    f"                      "   # 22X
                    f"{alt_top:7.2f}{p_top:8.3f}{t_top:7.2f}"
                    f"{clwc:7.3f}"
                )
            lines.append(layer_line)

            # ---- molecular amounts (FORMAT 978: 8E15.7) ----
            # WBRODL = dry-air column [molec/cm²] — must be > 1
            dp = abs(p_bot - p_top)
            wbrodl = max(dp * COL_PER_HPA, 1.0)

            # H2O volume mixing ratio
            es = 6.1078 * np.exp(17.2693882 * (t - 273.16) / (t - 35.86))
            e_hpa = rh / 100.0 * es
            h2o_vmr = max(e_hpa / max(p, 1e-6), 1e-30)

            # WKL(1:7) + WBRODL → one 8E15.7 line
            mol_vals = [h2o_vmr]
            for m in range(2, 8):
                mol_vals.append(std_vmr.get(m, 1e-30))
            mol_vals.append(wbrodl)
            assert len(mol_vals) == 8
            lines.append("".join(f"{v:15.7E}" for v in mol_vals))

            # WKL(8:15) → second 8E15.7 line
            mol_vals2 = [std_vmr.get(m, 1e-30) for m in range(8, nmol + 1)]
            assert len(mol_vals2) == 8
            lines.append("".join(f"{v:15.7E}" for v in mol_vals2))

        return "\n".join(lines) + "\n"

    def _parse_output(self, output_text):
        """Parse MonoRTM MONORTM.OUT to extract brightness temperatures.

        MonoRTM outputs a table with header:
            PROF FREQ(GHz) BT(K) TMR(K) RAD(...) TRANS ...
        Note: FREQ is actually in MHz despite the "(GHz)" label.
        Data lines:
            1 22240.000  209.05049  278.41226  ...

        Returns:
            array of brightness temperatures [K], matching self.frequencies
        """
        tb = np.zeros(len(self.frequencies))

        lines = output_text.split("\n")
        data_lines = []

        in_table = False
        for line in lines:
            # Detect table header
            if "PROF" in line and "FREQ" in line and "BT" in line:
                in_table = True
                continue

            if not in_table or not line.strip():
                continue

            parts = line.split()
            if len(parts) < 3:
                continue

            # Line format: PROF FREQ(MHz) BT(K) TMR(K) ...
            try:
                prof_num = int(parts[0])
                freq_mhz = float(parts[1])
                bt_val = float(parts[2])

                # Sanity checks
                if freq_mhz > 1000 and 1 < bt_val < 400:
                    freq_ghz = freq_mhz / 1000.0
                    data_lines.append((freq_ghz, bt_val))
            except (ValueError, IndexError):
                continue

        # Match to our channels (nearest frequency within 0.5 GHz)
        for i, target_freq in enumerate(self.frequencies):
            best_match = None
            best_dist = float("inf")
            for freq, val in data_lines:
                dist = abs(freq - target_freq)
                if dist < best_dist:
                    best_dist = dist
                    best_match = val
            if best_match is not None and best_dist < 0.5:
                tb[i] = best_match

        return tb

    def simulate(self, profile):
        """Run MonoRTM for one atmospheric profile.

        Args:
            profile: dict with:
                T: temperature [K], shape (n_layers,)
                RH: relative humidity [%]
                CLWC: cloud liquid water [g/m^3] (optional)
                height: height [m]
                P_hPa: pressure [hPa] (optional)

        Returns:
            tb: brightness temperatures [K], shape (14,)
        """
        with tempfile.TemporaryDirectory() as tmpdir:
            # Write MONORTM.IN
            monortm_in = self._make_monortm_in(self.frequencies, tmpdir)
            with open(os.path.join(tmpdir, "MONORTM.IN"), "w") as f:
                f.write(monortm_in)

            # Write MONORTM_PROF.IN
            prof_in = self._make_monortm_prof_in(profile)
            with open(os.path.join(tmpdir, "MONORTM_PROF.IN"), "w") as f:
                f.write(prof_in)

            # Copy TAPE3 (symlink may not work across filesystems)
            if self.tape3_path and os.path.exists(self.tape3_path):
                shutil.copy2(self.tape3_path, os.path.join(tmpdir, "TAPE3"))

            # Run MonoRTM
            try:
                result = subprocess.run(
                    [self.monortm_path],
                    capture_output=True,
                    text=True,
                    cwd=tmpdir,
                    timeout=60,
                )
            except subprocess.TimeoutExpired:
                raise RuntimeError("MonoRTM execution timed out (60s)")

            # Check for errors
            if result.returncode != 0:
                stdout_sample = result.stdout[-500:] if result.stdout else "(empty)"
                stderr_sample = result.stderr[-500:] if result.stderr else "(empty)"
                raise RuntimeError(
                    f"MonoRTM failed with code {result.returncode}\n"
                    f"STDERR: {stderr_sample}\nSTDOUT: {stdout_sample}"
                )

            # Read output
            output_path = os.path.join(tmpdir, "MONORTM.OUT")
            if os.path.exists(output_path):
                with open(output_path, "r") as f:
                    output_text = f.read()
            else:
                output_text = result.stdout

            tb = self._parse_output(output_text)

        return tb

    def simulate_batch(self, profiles_dict):
        """Simulate BT for a batch of profiles.

        Args:
            profiles_dict: dict with arrays of shape (n_time, n_layers)
        Returns:
            tb_batch: shape (n_time, 14)
        """
        n_time = profiles_dict["T"].shape[0]
        n_chan = len(self.frequencies)
        tb_batch = np.zeros((n_time, n_chan))

        for t in range(n_time):
            profile = {
                "T": profiles_dict["T"][t],
                "RH": profiles_dict["RH"][t],
                "CLWC": profiles_dict["CLWC"][t],
                "P_hPa": profiles_dict["P"][t] if "P" in profiles_dict else
                    np.ones(len(profiles_dict["height"])) * 1013.0,
                "height": profiles_dict["height"],
            }
            tb_batch[t] = self.simulate(profile)

            if (t + 1) % 50 == 0:
                print(f"  MonoRTM: {t+1}/{n_time} profiles done")

        return tb_batch


# ============================================================
# Build helper
# ============================================================

def build_monortm_instructions():
    """Print instructions for building MonoRTM."""
    print("""
=================================================================
  MonoRTM Build Instructions
=================================================================

MonoRTM is now compiled and ready at:
  /Users/ink/test/mwr_retrieval/bin/monortm

To build from source:

  1. Clone:  git clone https://github.com/AER-RC/monoRTM.git
  2. Build:  bash build_monortm.sh

The build script compiles 16 Fortran files and links them.

=================================================================
""")


if __name__ == "__main__":
    # Quick test
    try:
        rtm = MonoRTM()
        print(f"MonoRTM found at: {rtm.monortm_path}")
        print(f"TAPE3 found at: {rtm.tape3_path}")

        # Test with standard atmosphere
        heights = np.array(config.HEIGHT_GRID)
        test_profile = {
            "T": 288.15 - 6.5 * heights / 1000.0,
            "RH": np.full_like(heights, 50.0),
            "CLWC": np.zeros_like(heights),
            "height": heights,
            "P_hPa": 1013.25 * np.exp(-heights / 8000.0),
        }

        print("\nRunning MonoRTM simulation...")
        tb = rtm.simulate(test_profile)
        print("\nBrightness Temperatures [K]:")
        for f, t in zip(config.ALL_CHANNELS, tb):
            band = "K" if f < 40 else "V"
            print(f"  {band}-band {f:.2f} GHz: {t:.2f} K")

    except FileNotFoundError as e:
        print(f"\n{e}")
        build_monortm_instructions()
